<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="App_Data\Media\Storage\catalog\**" />
    <Compile Remove="wwwroot\assets\js\customjs\**" />
    <Content Remove="App_Data\Media\Storage\catalog\**" />
    <Content Remove="wwwroot\assets\js\customjs\**" />
    <EmbeddedResource Remove="App_Data\Media\Storage\catalog\**" />
    <EmbeddedResource Remove="wwwroot\assets\js\customjs\**" />
    <None Remove="App_Data\Media\Storage\catalog\**" />
    <None Remove="wwwroot\assets\js\customjs\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.9" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="9.0.0" />
    <PackageReference Include="NPOI" Version="2.7.5" />
    <PackageReference Include="Rotativa.AspNetCore" Version="1.4.0" />
    <PackageReference Include="Serilog" Version="4.3.0" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="9.0.2" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="Serilog.Sinks.Graylog" Version="3.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Entegro.Infrastructure\Entegro.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="App_Data\Media\Storage\" />
    <Folder Include="App_Data\Media\Storage\document\" />
    <Folder Include="wwwroot\assets\img\brandicons\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Views\Product\_CreateOrUpdate.ProductVariantAttribute.cshtml" />
    <None Include="wwwroot\Rotativa\wkhtmltopdf.exe" />
  </ItemGroup>

</Project>
