//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArasCargoCustomerService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ArasCargoCustomerService.IArasCargoIntegrationService")]
    public interface IArasCargoIntegrationService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArasCargoIntegrationService/GetQueryDS", ReplyAction="http://tempuri.org/IArasCargoIntegrationService/GetQueryDSResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ArasCargoCustomerService.GetQueryDSResponse> GetQueryDSAsync(ArasCargoCustomerService.GetQueryDSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArasCargoIntegrationService/GetQueryXML", ReplyAction="http://tempuri.org/IArasCargoIntegrationService/GetQueryXMLResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ArasCargoCustomerService.GetQueryXMLResponse> GetQueryXMLAsync(ArasCargoCustomerService.GetQueryXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArasCargoIntegrationService/GetQueryJSON", ReplyAction="http://tempuri.org/IArasCargoIntegrationService/GetQueryJSONResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ArasCargoCustomerService.GetQueryJSONResponse> GetQueryJSONAsync(ArasCargoCustomerService.GetQueryJSONRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArasCargoIntegrationService/SetDataXML", ReplyAction="http://tempuri.org/IArasCargoIntegrationService/SetDataXMLResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ArasCargoCustomerService.SetDataXMLResponse> SetDataXMLAsync(ArasCargoCustomerService.SetDataXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArasCargoIntegrationService/CallCourier", ReplyAction="http://tempuri.org/IArasCargoIntegrationService/CallCourierResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ArasCargoCustomerService.CallCourierResponse> CallCourierAsync(ArasCargoCustomerService.CallCourierRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CustCargoInfo.Models")]
    public partial class CallCourierReturn
    {
        
        private int countField;
        
        private bool countFieldSpecified;
        
        private int resultField;
        
        private bool resultFieldSpecified;
        
        private string resultMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int count
        {
            get
            {
                return this.countField;
            }
            set
            {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool countSpecified
        {
            get
            {
                return this.countFieldSpecified;
            }
            set
            {
                this.countFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool resultSpecified
        {
            get
            {
                return this.resultFieldSpecified;
            }
            set
            {
                this.resultFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string resultMessage
        {
            get
            {
                return this.resultMessageField;
            }
            set
            {
                this.resultMessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetQueryDS", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetQueryDSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string loginInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string queryInfo;
        
        public GetQueryDSRequest()
        {
        }
        
        public GetQueryDSRequest(string loginInfo, string queryInfo)
        {
            this.loginInfo = loginInfo;
            this.queryInfo = queryInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetQueryDSResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetQueryDSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ArasCargoCustomerService.ArrayOfXElement GetQueryDSResult;
        
        public GetQueryDSResponse()
        {
        }
        
        public GetQueryDSResponse(ArasCargoCustomerService.ArrayOfXElement GetQueryDSResult)
        {
            this.GetQueryDSResult = GetQueryDSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetQueryXML", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetQueryXMLRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string loginInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string queryInfo;
        
        public GetQueryXMLRequest()
        {
        }
        
        public GetQueryXMLRequest(string loginInfo, string queryInfo)
        {
            this.loginInfo = loginInfo;
            this.queryInfo = queryInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetQueryXMLResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetQueryXMLResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetQueryXMLResult;
        
        public GetQueryXMLResponse()
        {
        }
        
        public GetQueryXMLResponse(string GetQueryXMLResult)
        {
            this.GetQueryXMLResult = GetQueryXMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetQueryJSON", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetQueryJSONRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string loginInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string queryInfo;
        
        public GetQueryJSONRequest()
        {
        }
        
        public GetQueryJSONRequest(string loginInfo, string queryInfo)
        {
            this.loginInfo = loginInfo;
            this.queryInfo = queryInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetQueryJSONResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetQueryJSONResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetQueryJSONResult;
        
        public GetQueryJSONResponse()
        {
        }
        
        public GetQueryJSONResponse(string GetQueryJSONResult)
        {
            this.GetQueryJSONResult = GetQueryJSONResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetDataXML", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SetDataXMLRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string loginInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string queryInfo;
        
        public SetDataXMLRequest()
        {
        }
        
        public SetDataXMLRequest(string loginInfo, string queryInfo)
        {
            this.loginInfo = loginInfo;
            this.queryInfo = queryInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetDataXMLResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SetDataXMLResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SetDataXMLResult;
        
        public SetDataXMLResponse()
        {
        }
        
        public SetDataXMLResponse(string SetDataXMLResult)
        {
            this.SetDataXMLResult = SetDataXMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CallCourier", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CallCourierRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string loginInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string queryInfo;
        
        public CallCourierRequest()
        {
        }
        
        public CallCourierRequest(string loginInfo, string queryInfo)
        {
            this.loginInfo = loginInfo;
            this.queryInfo = queryInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CallCourierResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CallCourierResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ArasCargoCustomerService.CallCourierReturn CallCourierResult;
        
        public CallCourierResponse()
        {
        }
        
        public CallCourierResponse(ArasCargoCustomerService.CallCourierReturn CallCourierResult)
        {
            this.CallCourierResult = CallCourierResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IArasCargoIntegrationServiceChannel : ArasCargoCustomerService.IArasCargoIntegrationService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ArasCargoIntegrationServiceClient : System.ServiceModel.ClientBase<ArasCargoCustomerService.IArasCargoIntegrationService>, ArasCargoCustomerService.IArasCargoIntegrationService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ArasCargoIntegrationServiceClient() : 
                base(ArasCargoIntegrationServiceClient.GetDefaultBinding(), ArasCargoIntegrationServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpsBinding_IArasCargoIntegrationService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ArasCargoIntegrationServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ArasCargoIntegrationServiceClient.GetBindingForEndpoint(endpointConfiguration), ArasCargoIntegrationServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ArasCargoIntegrationServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ArasCargoIntegrationServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ArasCargoIntegrationServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ArasCargoIntegrationServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ArasCargoIntegrationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ArasCargoCustomerService.GetQueryDSResponse> ArasCargoCustomerService.IArasCargoIntegrationService.GetQueryDSAsync(ArasCargoCustomerService.GetQueryDSRequest request)
        {
            return base.Channel.GetQueryDSAsync(request);
        }
        
        public System.Threading.Tasks.Task<ArasCargoCustomerService.GetQueryDSResponse> GetQueryDSAsync(string loginInfo, string queryInfo)
        {
            ArasCargoCustomerService.GetQueryDSRequest inValue = new ArasCargoCustomerService.GetQueryDSRequest();
            inValue.loginInfo = loginInfo;
            inValue.queryInfo = queryInfo;
            return ((ArasCargoCustomerService.IArasCargoIntegrationService)(this)).GetQueryDSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ArasCargoCustomerService.GetQueryXMLResponse> ArasCargoCustomerService.IArasCargoIntegrationService.GetQueryXMLAsync(ArasCargoCustomerService.GetQueryXMLRequest request)
        {
            return base.Channel.GetQueryXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<ArasCargoCustomerService.GetQueryXMLResponse> GetQueryXMLAsync(string loginInfo, string queryInfo)
        {
            ArasCargoCustomerService.GetQueryXMLRequest inValue = new ArasCargoCustomerService.GetQueryXMLRequest();
            inValue.loginInfo = loginInfo;
            inValue.queryInfo = queryInfo;
            return ((ArasCargoCustomerService.IArasCargoIntegrationService)(this)).GetQueryXMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ArasCargoCustomerService.GetQueryJSONResponse> ArasCargoCustomerService.IArasCargoIntegrationService.GetQueryJSONAsync(ArasCargoCustomerService.GetQueryJSONRequest request)
        {
            return base.Channel.GetQueryJSONAsync(request);
        }
        
        public System.Threading.Tasks.Task<ArasCargoCustomerService.GetQueryJSONResponse> GetQueryJSONAsync(string loginInfo, string queryInfo)
        {
            ArasCargoCustomerService.GetQueryJSONRequest inValue = new ArasCargoCustomerService.GetQueryJSONRequest();
            inValue.loginInfo = loginInfo;
            inValue.queryInfo = queryInfo;
            return ((ArasCargoCustomerService.IArasCargoIntegrationService)(this)).GetQueryJSONAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ArasCargoCustomerService.SetDataXMLResponse> ArasCargoCustomerService.IArasCargoIntegrationService.SetDataXMLAsync(ArasCargoCustomerService.SetDataXMLRequest request)
        {
            return base.Channel.SetDataXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<ArasCargoCustomerService.SetDataXMLResponse> SetDataXMLAsync(string loginInfo, string queryInfo)
        {
            ArasCargoCustomerService.SetDataXMLRequest inValue = new ArasCargoCustomerService.SetDataXMLRequest();
            inValue.loginInfo = loginInfo;
            inValue.queryInfo = queryInfo;
            return ((ArasCargoCustomerService.IArasCargoIntegrationService)(this)).SetDataXMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ArasCargoCustomerService.CallCourierResponse> ArasCargoCustomerService.IArasCargoIntegrationService.CallCourierAsync(ArasCargoCustomerService.CallCourierRequest request)
        {
            return base.Channel.CallCourierAsync(request);
        }
        
        public System.Threading.Tasks.Task<ArasCargoCustomerService.CallCourierResponse> CallCourierAsync(string loginInfo, string queryInfo)
        {
            ArasCargoCustomerService.CallCourierRequest inValue = new ArasCargoCustomerService.CallCourierRequest();
            inValue.loginInfo = loginInfo;
            inValue.queryInfo = queryInfo;
            return ((ArasCargoCustomerService.IArasCargoIntegrationService)(this)).CallCourierAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IArasCargoIntegrationService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IArasCargoIntegrationService))
            {
                return new System.ServiceModel.EndpointAddress("https://customerservices.araskargo.com.tr/ArasCargoCustomerIntegrationService/Ara" +
                        "sCargoIntegrationService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ArasCargoIntegrationServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpsBinding_IArasCargoIntegrationService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ArasCargoIntegrationServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpsBinding_IArasCargoIntegrationService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpsBinding_IArasCargoIntegrationService,
        }
    }
    
    [System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil-lib", "8.0.0.0")]
    public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
        
        public ArrayOfXElement()
        {
        }
        
        public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes
        {
            get
            {
                return this.nodesList;
            }
        }
        
        public virtual System.Xml.Schema.XmlSchema GetSchema()
        {
            throw new System.NotImplementedException();
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
            for (
            ; e.MoveNext(); 
            )
            {
                ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader)
        {
            for (
            ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
            )
            {
                if ((reader.NodeType == System.Xml.XmlNodeType.Element))
                {
                    System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                    ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                    Nodes.Add(elem);
                }
                else
                {
                    reader.Skip();
                }
            }
        }
    }
}
